name: semver Tagging

on:
  push:
    tags:
      - v*

jobs:
  tag-master-with-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - run: |
          docker pull liberoadmin/reviewer-submission:master-${{ github.sha }}
          docker pull liberoadmin/reviewer-xpub-postgres:master-${{ github.sha }}
          ./scripts/github/retag-and-push.sh reviewer-submission master-${{ github.sha }}
          ./scripts/github/retag-and-push.sh reviewer-xpub-postgres master-${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
