version: '3'
services:
  client:
    image: liberoadmin/reviewer-client:latest
    ports:
      - "${CLIENT_PORT}:9000"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_API_URL: ${CLIENT_API_URL}
      CLIENT_API_PROXY_URL: "http://reviewer-mocks:3003/graphql"
      CLIENT_AUTH_PROXY_URL: "http://reviewer-mocks:3003/authenticate/"
      CONTINUUM_LOGIN_URL: ${CONTINUUM_LOGIN_URL}

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks
    ports:
      - "3003:3003"
    environment:
      PORT: "3003"
      CONTINUUM_LOGIN_JWT_SECRET: "some_secret_from_journal"
      CONTINUUM_LOGIN_REDIRECT_URL: "http://localhost:9000/auth-redirect"
      CONTINUUM_AUTH_JWT_SECRET: "some_secret_from_auth_service"
      CONTINUUM_AUTH_REDIRECT_URL: "http://localhost:9000/login"
