version: '3'
services: 
  client:
    image: libero/reviewer-client:local
    ports:
      - "${CLIENT_PORT}:9000"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_API_URL: ${CLIENT_API_URL}
      CLIENT_API_PROXY_URL: "http://localhost:3003"
      CLIENT_AUTH_PROXY_URL: "http://localhost:3003"
      CONTINUUM_LOGIN_URL: ${CONTINUUM_LOGIN_URL}

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks
    ports:
      - "3003:3003"
    environment:
      PORT: "3003"
      CONTINUUM_LOGIN_JWT_SECRET: "some_secret_from_journal"
      CONTINUUM_LOGIN_REDIRECT_URL: "http://localhost:3003/authenticate"
      CONTINUUM_AUTH_JWT_SECRET: "some_secret_from_auth_service"
      CONTINUUM_AUTH_REDIRECT_URL: "http://localhost:9000/login"