version: '3'
services:
  # Client
  client_source:
    build:
      context: './'
      dockerfile: 'Dockerfile.source'
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer-client_source:${IMAGE_TAG}

  reviewer-client:
    build:
      context: './'
      dockerfile: "Dockerfile.application"
      args:
        image_tag: "${IMAGE_TAG}"
    image: libero/reviewer-client:${IMAGE_TAG}
    depends_on:
      - client_source
