FROM node:10-alpine

WORKDIR /app

COPY globals.d.ts index.html index.tsx .babelrc .eslintrc.js .eslintignore .prettierrc.js webpack.parts.js jest.config.js tsconfig.json webpack.config.js config.ts ./

COPY test-utils/ test-utils/
COPY webpack/ webpack/
COPY src/ ./src/
COPY .storybook/ ./.storybook
COPY package.json .
COPY yarn.lock .

RUN yarn

