version: '3.4'
services:
  reviewer-client:
    container_name: reviewer-client_app
    build:
      context: './'
      target: prod
    networks:
      - "reviewer"
    image: libero/reviewer-client:${IMAGE_TAG}

  nginx:
    container_name: reviewer-client_nginx
    image: nginx:stable-alpine@sha256:0dfc8450deb8c7f06fbaac27e453ac3262df7d3a93639c4e2f48ee39434ec017
    networks:
      - "reviewer"
    ports:
      - '9000:9000'
    volumes:
      - ./config/nginx-proxies/nginx.ci.conf:/etc/nginx/nginx.conf

  reviewer-mocks:
    container_name: reviewer-client_mocks
    image: liberoadmin/reviewer-mocks:latest
    ports:
      - "3003:3003"
    volumes:
      - ./config/reviewer-mocks:/etc/reviewer/:z
    networks:
      - "reviewer"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost 3003'
      interval: 3s
      timeout: 10s
      retries: 3
      
networks:
  reviewer:
    external:
      name: "reviewer"
      