version: '3.4'
services:
  reviewer-client:
    container_name: reviewer-client_app
    build:
      context: './'
      target: dev
    image: libero/reviewer-client:${IMAGE_TAG:-local}
    environment: 
      CLIENT_PORT: 9000
      NEW_RELIC_CLIENT_LICENSE_KEY: ''
      NEW_RELIC_CLIENT_APP_ID: ''
    volumes:
      - ./globals.d.ts:/app/globals.d.ts
      - ./.eslintignore:/app/.eslintignore
      - ./.eslintrc.js:/app/.eslintrc.js
      - ./.prettierrc.js:/app/.prettierrc.js
      - ./jest.config.js:/app/jest.config.js
      - ./src/:/app/src
      - ./package.json:/app/package.json
      - ./yarn.json:/app/yarn.json
      - ./tests/:/app/tests
      - ./tsconfig.json:/app/tsconfig.json
      - ./index.ts:/app/index.ts
      - ./index.ejs:/app/index.ejs
      - ./babelrc:/app/babelrc
      - ./webpack.parts.js:/app/webpack.parts.js
      - ./webpack.config.js:/app/webpack.config.js
    networks:
      - "reviewer"
      
  reviewer-mocks:
    container_name: reviewer-client_mocks
    image: liberoadmin/reviewer-mocks:latest
    ports:
      - "3003:3003"
    volumes:
      - ./config/reviewer-mocks:/etc/reviewer/:z
    networks:
      - "reviewer"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost 3003'
      interval: 3s
      timeout: 10s
      retries: 3
      
networks:
  reviewer:
    external:
      name: "reviewer"
      