version: '3.4'
services:
  nginx:
    volumes:
      - ./config/nginx-proxies/nginx.ci.localhost.conf:/etc/nginx/nginx.conf

  reviewer-mocks:
    volumes:
      - ./config/reviewer-mocks/config.default.json:/etc/reviewer/config.json
      