FROM node:12-alpine@sha256:5646d1e5bc470500414feb3540186c02845db0e0e1788621c271fbf3a0c1830d

WORKDIR /app

COPY globals.d.ts index.ejs index.tsx .babelrc .eslintrc.js .eslintignore .prettierrc.js webpack.parts.js jest.config.js tsconfig.json webpack.config.js config.ts ./

COPY test-utils/ test-utils/
COPY webpack/ webpack/
COPY src/ ./src/
COPY .storybook/ ./.storybook
COPY package.json .
COPY yarn.lock .

RUN yarn

