version: '3'
services: 
  client:
    image: libero/reviewer-client:local
    ports:
      - "${CLIENT_PORT}:9000"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_API_URL: ${CLIENT_API_URL}
      CLIENT_API_PROXY_URL: "http://server:3000"
      CONTINUUM_LOGIN_URL: ${CONTINUUM_LOGIN_URL}
    networks:
      - "infra_api"

networks:
  infra_api:
    external:
      name: "infra_api"
