version: '3'
services:
  client:
    image: libero/reviewer-client:${IMAGE_TAG}
    ports:
      - "${CLIENT_PORT}:9000"
    volumes:
      - ./config/:/etc/reviewer/:z

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:latest
    ports:
      - "3003:3003"
    volumes:
      - ./config/reviewer-mocks:/etc/reviewer/:z
