FROM nginx:1-alpine
ARG image_tag=latest

MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>
WORKDIR /app

RUN apk add jq

COPY deployment/nginx.conf.template /etc/nginx/nginx.conf.template
COPY dist/ /usr/share/nginx/html
COPY scripts/build-config.sh /app

EXPOSE 80

HEALTHCHECK --interval=1m --timeout=1s \
	CMD echo -e "GET /health\n\n" | nc localhost:9000

CMD ["/bin/sh", "/app/build-config.sh"]
