version: '3.4'
services:
  reviewer-client:
    container_name: reviewer-client_app

  nginx:
    container_name: reviewer-client_nginx
    image: nginx:stable-alpine@sha256:0dfc8450deb8c7f06fbaac27e453ac3262df7d3a93639c4e2f48ee39434ec017
    networks:
      - "reviewer"
    ports:
      - '9000:9000'
    volumes:
      - ./config/nginx/nginx.test.conf:/etc/nginx/nginx.conf