version: '3'
services: 
  client:
    image: libero/reviewer-client:local
    ports:
      - "${CLIENT_PORT}:9000"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_API_URL: ${CLIENT_API_URL}
      CLIENT_API_PROXY_URL: "http://localhost:3000"
      CLIENT_AUTH_PROXY_URL: "http://localhost:3000"
      CONTINUUM_LOGIN_URL: ${CONTINUUM_LOGIN_URL}

  mock-continuum-login:
    image: liberoadmin/mock-continuum-login:latest
    ports:
      - "3000:3000"
    environment:
      CONTINUUM_LOGIN_URL: "http://localhost:3000/submit"
      CONTINUUM_LOGIN_PORT: 3000
      CONTINUUM_LOGIN_JWT_SECRET: "some_secret_from_journal"