name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
env:
  IMAGE_TAG: ${{ github.sha }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - name: Lint
        run: make lint
      - name: Unit Test
        run: make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - name: Build
        run: make build
      - name: Save Docker images
        run: |
          mkdir -p docker-image
          docker save -o docker-image/reviewer-client.tar libero/reviewer-client:${IMAGE_TAG}
          gzip docker-image/reviewer-client.tar
      - name: Upload prod Docker image
        uses: actions/upload-artifact@v1
        with:
          name: docker-image
          path: docker-image
  browser-test:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - name: yarn
        run: yarn
      - name: Download Docker image artifact
        uses: actions/download-artifact@v1
        with:
          name: docker-image
      - name: Load Docker image
        run: |
          gunzip docker-image/reviewer-client.tar.gz
          docker load -i docker-image/reviewer-client.tar
      - name: Create Config
        run: make setup
      - name: Start services
        run: make start
      - name: Browser Test
        run: make test_browser
  deploy-image:
    runs-on: ubuntu-latest
    needs: browser-test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v1
        with:
          name: docker-image
      - name: Load Docker image
        run: |
          gunzip docker-image/reviewer-client.tar.gz
          docker load -i docker-image/reviewer-client.tar
      - name: Push image
        run: .scripts/github/push-image.sh reviewer-client
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
