name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

steps:
  - uses: actions/checkout@v1
  - uses: actions/setup-node@v1
  - run: make lint
  - run: make test
  
