name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
env:
  IMAGE_TAG: ${{ github.sha }}
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - name: Lint
        run: make lint
      - name: Unit Test
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and tarball container image
        run: |
          make build_prod
          docker save -o reviewer-client.tar libero/reviewer-client:${IMAGE_TAG}
      - uses: actions/upload-artifact@v2
        with:
          name: reviewer-client.tar
          path: reviewer-client.tar

  browserstack-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [
          'browserstack:safari@13.1:OS X Catalina',
          'browserstack:safari@12.1:OS X Mojave',
          'browserstack:safari@11.1:OS X High Sierra',
          'browserstack:edge@18.0:Windows 10',
          'browserstack:edge@81.0:Windows 10'
          ]
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_PROJECT_NAME: libero-reviewer-client
      BROWSERSTACK_BUILD_ID: ${{github.ref}}-${{github.sha}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - uses: actions/download-artifact@v2
      - name: Setup client with mocks
        run: |
          docker load -i reviewer-client.tar/reviewer-client.tar
          yarn
          make setup
          make start_ci_localhost
      - run: yarn testcafe '${{ matrix.browser }}' 'tests/**/*.browser.ts'

  browsertest-and-push-images:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/download-artifact@v2
      - name: Setup client with mocks
        run: |
          docker load -i reviewer-client.tar/reviewer-client.tar
          make setup
          make start_ci
      - run: make build_browsertest
      - run: make test_chromium
      - run: make test_firefox
      - name: Push images to docker hub
        if: github.ref == 'refs/heads/master'
        run: |
          .scripts/github/retag-and-push.sh reviewer-client $IMAGE_TAG
          .scripts/github/retag-and-push.sh reviewer-browsertests $IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
