name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
env:
  IMAGE_TAG: ${{ github.sha }}
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - name: Lint
        run: make lint
      - name: Unit Test
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: libero
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: libero/reviewer-client/reviewer-client
          #image_tag: ${{ github.sha }}
          push_git_tag: true
          registry: docker.pkg.github.com
          build_extra_args: "--build-arg=image_tag=${IMAGE_TAG}"

  browserstack-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [
          'browserstack:safari@13.1:OS X Catalina',
          'browserstack:safari@12.1:OS X Mojave',
          'browserstack:safari@11.1:OS X High Sierra',
          'browserstack:chrome@83.0:Windows 10',
          'browserstack:firefox@76.0:Windows 10',
          'browserstack:edge@81.0:Windows 10'
          ]
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_PROJECT_NAME: libero-reviewer-client
      BROWSERSTACK_BUILD_ID: ${{ github.ref }}-${{ github.event.pull_request.head.sha }}
      BROWSERSTACK_NETWORK_LOGS: true
      BROWSERSTACK_CONSOLE: 'verbose'
      BROWSERSTACK_USE_AUTOMATE: "1"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - name: Setup client with mocks
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/libero/reviewer-client/reviewer-client:${IMAGE_TAG}
          yarn
          make setup
          make start_ci_localhost
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: ${{ matrix.browser }}
        run: |
          yarn testcafe --page-load-timeout 30000 --assertion-timeout 30000 '${{ matrix.browser }}' 'tests/**/*.browser.ts'

  browsertest-container:
    needs: [test, build]
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup client with mocks
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/libero/reviewer-client/reviewer-client:${IMAGE_TAG}
          make setup
          make start_ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: make build_browsertest
      - run: make test_chromium

  browsertest-and-push-images:
    needs: [test, build, browserstack-tests]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup client with mocks
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/libero/reviewer-client/reviewer-client:${IMAGE_TAG}
          make setup
          make start_ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: make build_browsertest
      - run: make test_chromium
      - name: Push images to docker hub
        run: |
          .scripts/github/retag-and-push.sh reviewer-client $IMAGE_TAG
          .scripts/github/retag-and-push.sh reviewer-browsertests $IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
