name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
env:
  IMAGE_TAG: ${{ github.sha }}
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - name: Lint
        run: make lint
      - name: Unit Test
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12.15'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-client-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-client-
      - name: Build and tarball container image
        run: |
          make build_prod
          docker save -o reviewer-client.tar libero/reviewer-client:${IMAGE_TAG}
      - uses: actions/upload-artifact@v2
        with:
          path: reviewer-client.tar

  browser-test:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/download-artifact@v2
      - name: Setup client with mocks; build, run and save browsertest container
        run: |
          docker load -i reviewer-client.tar
          make setup
          make start_ci
          make test_browser_containerized
          docker save -o reviewer-browsertests.tar libero/reviewer-browsertests:${IMAGE_TAG}
      - uses: actions/upload-artifact@v2
        with:
          path: reviewer-browsertests.tar

  upload-images:
    runs-on: ubuntu-latest
    needs: browser-test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/download-artifact@v2
      - name: Load Docker images
        run: |
          docker load -i reviewer-client.tar
          docker load -i reviewer-browsertests.tar
      - name: Push images to hub.docker.com
        run: |
          .scripts/github/retag-and-push.sh reviewer-client $IMAGE_TAG
          .scripts/github/retag-and-push.sh reviewer-browsertests $IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
